[build]
  publish = "build"
  command = "npx browserslist@latest --update-db && CI=false npm install --legacy-peer-deps && npm run build"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "build"
